android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US
kotlin.daemon.jvmargs=-Xmx2g -Duser.language=en -Duser.country=US
kotlin.compiler.execution.strategy=in-process
android.builtInKotlin=false
android.newDsl=false
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL,MULTIDEX_NOT_NEEDED
android.useFullClasspathForDexingTransform=true
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=true
