org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseParallelGC -Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US
org.gradle.parallel=true
org.gradle.caching=true
ksp.incremental=true
android.disallowKotlinSourceSets=false
kotlin.code.style=official
org.gradle.java.home=C\:/boss/jdk-26.0.2
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL,MULTIDEX_NOT_NEEDED
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
