android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx4g -Dkotlin.daemon.client.alive.check.resend.interval.ms=300 -Dkotlin.daemon.client.alive.check.timeout.ms=1000
kotlin.compiler.execution.strategy=in-process
kapt.use.worker.api=false
android.builtInKotlin=false
android.newDsl=false
android.useFullClasspathForDexingTransform=true
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=true
org.gradle.workers.max=2
